server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    hostname: auth-service
jwt:
  secret: lms-super-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    com.lms: INFO

logstash:
  host: logstash
  port: 5044
